= org/apache/bval/jsr/job/ConstraintValidatorContextImpl$ConstraintViolationBuilderImpl.class

 - link:ConstraintValidatorContextImpl$ConstraintViolationBuilderImpl-asmified.java[Asmified]

== References

 - javax.validation.ConstraintValidatorContext - 3
 - javax.validation.metadata.ParameterDescriptor - 2
 - javax.validation.ValidationException - 2
 - javax.validation.ElementKind - 2
 - javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder$NodeBuilderDefinedContext - 2
 - javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder - 1
 - javax.validation.metadata.CrossParameterDescriptor - 1
 - javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder$ContainerElementNodeBuilderCustomizableContext - 1
 - javax.validation.metadata.ElementDescriptor - 1
 - javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder$LeafNodeBuilderCustomizableContext - 1
 - javax.validation.Path$Node - 1
 - javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder$NodeBuilderCustomizableContext - 1
 - javax.validation.Path - 1
